### ISSUE TITLE
{Fixed* Question}

### ISSUE THREAD

**Issue by Glatrix** [DarkDevvv/HUE.GGKrunkerCheat#1]
Doesn't Work... but nice work

**Comment by DarkDevvv** [comment]
Was Patched update coming today

**Comment by DarkDevvv** [comment]
> Doesn't Work... but nice work

Justed Updated Should Work https://github.com/DarkDevvv/HUE.GGKrunkerCheat/blob/main/hueggkrunkerhack.user.js
Join The Discord https://discord.gg/fYeZHrCyQU

**Comment by Glatrix** [comment]
nice... Im new to the coding thing... how do you get your source code for Krunker? Ive tried downloading all mirrors for the website but opening index.html always gets stuck on loading.
